[package]
name = "crypto-keystore-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
crypto-keystore-rs = { path = "..", default-features = false }
serde_json = "1"
rand = "0.8"
hex = "0.4"

[features]
default = ["ethereum", "solana"]
ethereum = ["crypto-keystore-rs/ethereum"]
solana = ["crypto-keystore-rs/solana"]

[[bin]]
name = "imports"
path = "fuzz_targets/imports.rs"
test = false
doc = false
bench = false

[[bin]]
name = "authenticated"
path = "fuzz_targets/authenticated.rs"
test = false
doc = false
bench = false
